source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!
platform :ios, '11.0'

target 'ZZCardView_Example' do
  pod 'ZZCardView', :path => '../'

  target 'ZZCardView_Tests' do
    inherit! :search_paths

    
  end
end
